// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypxlqnfyahjdqdmajbft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlweGxxbmZ5YWhqZHFkbWFqYmZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDEwNjUsImV4cCI6MjA3MjU3NzA2NX0.gRYFTfJEpMZlkb8xOPoCiKdspsdrJoeX2FSRkfOAbNA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});